# \u9879\u76EE\u7AEF\u53E3
server:
  port: 8080
# \u8FDE\u63A5\u6C60\u914D\u7F6E
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_vue?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

# jwt\u914D\u7F6E
jwt:
  secret: hahahahage  #\u5BC6\u5319KEY
  expire: 30  #\u8FC7\u671F\u65F6\u95F4 \u5355\u4F4D\u5206\u949F
  tokenHeader: Authorization  #\u8BF7\u6C42\u5934
  tokenHead: WangXin3-  #Token\u524D\u7F00\u5B57\u7B26

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml #\u6620\u5C04\u6587\u4EF6\u914D\u7F6E
  configuration:
    map-underscore-to-camel-case: true #\u5F00\u542F\u9A7C\u5CF0\u547D\u540D